proxy,status,location,real_location,error
https://43.153.5.215,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d06d40>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://154.0.12.163,0,South Africa,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d04820>: Failed to establish a new connection: [Errno 111] Connection refused')))"
https://103.27.111.156,0,Hong Kong,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectionResetError(104, 'Connection reset by peer')))"
https://168.138.55.69,0,Japan,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)'))))"
https://171.228.148.165,0,Vietnam,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1d4b0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
https://157.10.52.230,0,Vietnam,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d079a0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://143.110.232.177,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1d510>, 'Connection to 143.110.232.177 timed out. (connect timeout=5)')))"
https://157.66.16.44,0,Indonesia,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1f6d0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
https://20.27.86.185,0,Japan,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1e8c0>, 'Connection to 20.27.86.185 timed out. (connect timeout=5)')))"
https://8.215.108.194,0,Indonesia,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d07bb0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://219.65.73.81,0,India,Failed,"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
https://47.74.226.8,0,Singapore,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ReadTimeoutError(""HTTPSConnectionPool(host='ipinfo.io', port=443): Read timed out. (read timeout=5)"")))"
http://23.82.137.162,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1e470>, 'Connection to 23.82.137.162 timed out. (connect timeout=5)')))"
https://47.252.29.28,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1fe20>, 'Connection to 47.252.29.28 timed out. (connect timeout=5)')))"
http://78.28.152.113,0,Bosnia and Herzegovina,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d05120>, 'Connection to 78.28.152.113 timed out. (connect timeout=5)')))"
http://160.22.193.142,0,Indonesia,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1f1f0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
https://18.223.25.15,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1e2f0>, 'Connection to 18.223.25.15 timed out. (connect timeout=5)')))"
https://13.36.104.85,0,France,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d06ad0>, 'Connection to 13.36.104.85 timed out. (connect timeout=5)')))"
https://13.37.73.214,0,France,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d078b0>, 'Connection to 13.37.73.214 timed out. (connect timeout=5)')))"
http://138.68.235.51,0,United States,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d05240>, 'Connection to 138.68.235.51 timed out. (connect timeout=5)')))"
