proxy,status,location,real_location,error
162.212.156.192:10010,0,US,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d04250>: Failed to establish a new connection: [Errno 111] Connection refused')))"
135.181.30.244:41856,0,FI,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d07670>: Failed to establish a new connection: [Errno 111] Connection refused')))"
46.4.252.237:9050,0,DE,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d04f70>: Failed to establish a new connection: [Errno 111] Connection refused')))"
104.21.6.88:80,0,CA,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))"
203.160.59.249:4145,0,ID,Failed,"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
41.70.106.1:5678,0,MW,Failed,"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
181.115.17.146:8080,0,HN,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b582b0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
185.198.181.140:5678,0,ES,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d079d0>, 'Connection to 185.198.181.140 timed out. (connect timeout=5)')))"
81.70.93.54:2079,0,CN,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1fe80>: Failed to establish a new connection: [Errno 111] Connection refused')))"
190.4.205.226:4153,0,CL,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1d210>, 'Connection to 190.4.205.226 timed out. (connect timeout=5)')))"
114.104.135.106:50071,0,CN,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1e0b0>, 'Connection to 114.104.135.106 timed out. (connect timeout=5)')))"
103.212.93.254:45639,0,IN,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1df90>: Failed to establish a new connection: [Errno 111] Connection refused')))"
181.204.217.194:4145,0,CO,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1edd0>, 'Connection to 181.204.217.194 timed out. (connect timeout=5)')))"
45.56.97.239:37669,0,US,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b58a60>: Failed to establish a new connection: [Errno 111] Connection refused')))"
43.134.167.51:443,0,SG,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d04400>: Failed to establish a new connection: [Errno 111] Connection refused')))"
111.68.31.130:3128,0,ID,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d05330>: Failed to establish a new connection: [Errno 111] Connection refused')))"
190.181.23.10:4153,0,BO,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1e830>: Failed to establish a new connection: [Errno 111] Connection refused')))"
103.70.204.1:59311,0,IN,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d07640>: Failed to establish a new connection: [Errno 111] Connection refused')))"
185.215.53.193:3629,0,AM,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b59240>, 'Connection to 185.215.53.193 timed out. (connect timeout=5)')))"
172.104.233.184:8080,0,DE,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1f820>, 'Connection to 172.104.233.184 timed out. (connect timeout=5)')))"
